import { Poppins } from "next/font/google";
import { Geist_Mono } from "next/font/google"; // Import Geist_Mono

import "./globals.css";


const poppins = Poppins({variable: "--font-poppins", subsets:['latin'],weight:['300','400','500','600','700','800','900']})
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function ProfileLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        
        <div className="wrapper">
        <div className="row">
          <h1>profle header</h1>
        </div>
        {children}
        <div className="row">
          <h1>profile footer</h1>
        </div>
        </div>
      </body>
    </html>
  );
}
