pipeline {
    agent any 
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/uthpala99131/IBILLS-Auto-Lanka'
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat 'docker build -t uthpala99/ibills-pjct:%BUILD_NUMBER% .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                pipeline {
    agent any 
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/uthpala99131/IBILLS-Auto-Lanka'
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat 'docker build -t uthpala99/ibills-pjct:%BUILD_NUMBER% .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'test-dockerhubpassword', variable: 'test-dockerhubpass')]) {
                    script {
                        bat "docker login -u uthpala99 -p %test-dockerhubpass%"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push uthpala99/ibills-pjct:%BUILD_NUMBER%'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
} {
                    script {
                        bat "docker login -u uthpala99 -p %samindocker%"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push uthpala99/nodeapp-cuban:%BUILD_NUMBER%'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}